
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:167 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1178 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      Product: Hardware Success Kit (Early Access)
      Component: Arm Compiler for Embedded 6.21
      Tool: armclang [5ec1fd00]
      
      Target: unspecified-arm-none-unspecified
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1178 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
      Product: Hardware Success Kit (Early Access)
      Component: Arm Compiler for Embedded 6.21
      Tool: armclang [5ec1fd00]
      
      Target: unspecified-arm-none-unspecified
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1178 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Checking whether the ASM compiler is Clang using "--version" did not match "(clang version)":
      Product: Hardware Success Kit (Early Access)
      Component: Arm Compiler for Embedded 6.21
      Tool: armclang [5ec1fd00]
      
      Target: unspecified-arm-none-unspecified
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1165 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Checking whether the ASM compiler is ARMClang using "--version" matched "armclang":
      Product: Hardware Success Kit (Early Access)
      Component: Arm Compiler for Embedded 6.21
      Tool: armclang [5ec1fd00]
      
      Target: unspecified-arm-none-unspecified
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Keil_v5/ARM/ARMCLANG/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags:  
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Keil_v5/ARM/ARMCLANG/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -c 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Keil_v5/ARM/ARMCLANG/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -Aa 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Keil_v5/ARM/ARMCLANG/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Keil_v5/ARM/ARMCLANG/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      0
      armclang: warning: '-mfloat-abi=hard': selected processor lacks floating point registers [-Wunsupported-abi]
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is ARMClang, found in:
        C:/Users/xavbou01/AVH-VSI/hello_video_vsi/tmp/hello_video_vsi/Corstone_300/lcd_out/CMakeFiles/3.29.1/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:167 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/xavbou01/AVH-VSI/hello_video_vsi/tmp/hello_video_vsi/Corstone_300/lcd_out/CMakeFiles/CMakeScratch/TryCompile-rn1vi3"
      binary: "C:/Users/xavbou01/AVH-VSI/hello_video_vsi/tmp/hello_video_vsi/Corstone_300/lcd_out/CMakeFiles/CMakeScratch/TryCompile-rn1vi3"
    cmakeVariables:
      CMAKE_C_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_FLAGS: "-mcpu=Cortex-M55 -mfloat-abi=hard"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "C:/ctools/cmsis-toolbox-windows-amd64/etc/CMakeASM"
      CMAKE_WARN_DEPRECATED: "FALSE"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/xavbou01/AVH-VSI/hello_video_vsi/tmp/hello_video_vsi/Corstone_300/lcd_out/CMakeFiles/CMakeScratch/TryCompile-rn1vi3'
        
        Run Build Command(s): C:/ctools/cmsis-toolbox-windows-amd64/bin/ninja.exe -v cmTC_d9f98
        [1/2] C:\\Keil_v5\\ARM\\ARMCLANG\\bin\\armclang.exe --target=arm-arm-none-eabi   -mcpu=Cortex-M55 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o -MF CMakeFiles\\cmTC_d9f98.dir\\CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o -c "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeCCompilerABI.c"
        Product: Hardware Success Kit (Early Access)
        Component: Arm Compiler for Embedded 6.21
        Tool: armclang [5ec1fd00]
        
        Target: arm-arm-none-eabi
         (in-process)
         "C:\\\\Keil_v5\\\\ARM\\\\ARMCLANG\\\\bin\\\\armclang.exe" -cc1 -triple thumbv8.1m.main-arm-none-eabihf -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign,preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m55 -target-feature +vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature +vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature +fp-armv8d16 -target-feature +fp-armv8d16sp -target-feature -fp-armv8sp -target-feature +fullfp16 -target-feature +fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-abi aapcs -mfloat-abi hard -debugger-tuning=gdb -fforce-dwarf-frame "-fdebug-compilation-dir=C:\\\\Users\\\\xavbou01\\\\AVH-VSI\\\\hello_video_vsi\\\\tmp\\\\hello_video_vsi\\\\Corstone_300\\\\lcd_out\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-rn1vi3" -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=C:\\\\Users\\\\xavbou01\\\\AVH-VSI\\\\hello_video_vsi\\\\tmp\\\\hello_video_vsi\\\\Corstone_300\\\\lcd_out\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-rn1vi3" -resource-dir "C:\\\\Keil_v5\\\\ARM\\\\ARMCLANG\\\\lib\\\\clang\\\\18" -dependency-file "CMakeFiles\\\\cmTC_d9f98.dir\\\\CMakeCCompilerABI.o.d" -MT CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o -sys-header-deps -canonical-system-headers -internal-isystem "C:\\\\Keil_v5\\\\ARM\\\\ARMCLANG\\\\bin\\\\..\\\\include" -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o -x c "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeCCompilerABI.c"
        Arm Compiler for Embedded 6.21 -cc1 default target aarch64-arm-none-eabi\x0d
        #include "..." search starts here:\x0d
        #include <...> search starts here:\x0d
         C:\\Keil_v5\\ARM\\ARMCLANG\\bin\\..\\include\x0d
        End of search list.\x0d
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Keil_v5\\ARM\\ARMCLANG\\bin\\armar.exe --create -cr libcmTC_d9f98.a  CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o && cd ."
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:134 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [C:/Keil_v5/ARM/ARMCLANG/bin/../include]
        end of search list found
        collapse include dir [C:/Keil_v5/ARM/ARMCLANG/bin/../include] ==> [C:/Keil_v5/ARM/ARMCLANG/include]
        implicit include dirs: [C:/Keil_v5/ARM/ARMCLANG/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:170 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:167 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(armlink\\.exe|;ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(armlink\\.exe|;ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        ignore line: [Change Dir: 'C:/Users/xavbou01/AVH-VSI/hello_video_vsi/tmp/hello_video_vsi/Corstone_300/lcd_out/CMakeFiles/CMakeScratch/TryCompile-rn1vi3']
        ignore line: []
        ignore line: [Run Build Command(s): C:/ctools/cmsis-toolbox-windows-amd64/bin/ninja.exe -v cmTC_d9f98]
        ignore line: [[1/2] C:\\Keil_v5\\ARM\\ARMCLANG\\bin\\armclang.exe --target=arm-arm-none-eabi   -mcpu=Cortex-M55 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o -MF CMakeFiles\\cmTC_d9f98.dir\\CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o -c "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeCCompilerABI.c"]
        ignore line: [Product: Hardware Success Kit (Early Access)]
        ignore line: [Component: Arm Compiler for Embedded 6.21]
        ignore line: [Tool: armclang [5ec1fd00]]
        ignore line: []
        ignore line: [Target: arm-arm-none-eabi]
        ignore line: [ (in-process)]
        ignore line: [ "C:\\\\Keil_v5\\\\ARM\\\\ARMCLANG\\\\bin\\\\armclang.exe" -cc1 -triple thumbv8.1m.main-arm-none-eabihf -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m55 -target-feature +vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature +vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature +fp-armv8d16 -target-feature +fp-armv8d16sp -target-feature -fp-armv8sp -target-feature +fullfp16 -target-feature +fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-abi aapcs -mfloat-abi hard -debugger-tuning=gdb -fforce-dwarf-frame "-fdebug-compilation-dir=C:\\\\Users\\\\xavbou01\\\\AVH-VSI\\\\hello_video_vsi\\\\tmp\\\\hello_video_vsi\\\\Corstone_300\\\\lcd_out\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-rn1vi3" -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=C:\\\\Users\\\\xavbou01\\\\AVH-VSI\\\\hello_video_vsi\\\\tmp\\\\hello_video_vsi\\\\Corstone_300\\\\lcd_out\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-rn1vi3" -resource-dir "C:\\\\Keil_v5\\\\ARM\\\\ARMCLANG\\\\lib\\\\clang\\\\18" -dependency-file "CMakeFiles\\\\cmTC_d9f98.dir\\\\CMakeCCompilerABI.o.d" -MT CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o -sys-header-deps -canonical-system-headers -internal-isystem "C:\\\\Keil_v5\\\\ARM\\\\ARMCLANG\\\\bin\\\\..\\\\include" -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o -x c "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeCCompilerABI.c"]
        ignore line: [Arm Compiler for Embedded 6.21 -cc1 default target aarch64-arm-none-eabi\x0d]
        ignore line: [#include "..." search starts here:\x0d]
        ignore line: [#include <...> search starts here:\x0d]
        ignore line: [ C:\\Keil_v5\\ARM\\ARMCLANG\\bin\\..\\include\x0d]
        ignore line: [End of search list.\x0d]
        ignore line: [[2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Keil_v5\\ARM\\ARMCLANG\\bin\\armar.exe --create -cr libcmTC_d9f98.a  CMakeFiles/cmTC_d9f98.dir/CMakeCCompilerABI.o && cd ."]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
